"""fixes customer model to postal_code

Revision ID: b37a2f4a5e23
Revises: 5aa983cce220
Create Date: 2021-12-20 19:48:13.586742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37a2f4a5e23'
down_revision = '5aa983cce220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postal_code', sa.String(), nullable=True))
    op.drop_column('customer', 'postcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('postcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'postal_code')
    # ### end Alembic commands ###
