"""makes changes to video model changes video title to title

Revision ID: be4b997d01cb
Revises: ff7b44c60256
Create Date: 2021-12-25 13:21:04.950526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4b997d01cb'
down_revision = 'ff7b44c60256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('video', 'video_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('video', 'title')
    # ### end Alembic commands ###
