"""makes changes to video model changes title to video title

Revision ID: ff7b44c60256
Revises: e64c54ee4e07
Create Date: 2021-12-25 13:18:14.505097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7b44c60256'
down_revision = 'e64c54ee4e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_title', sa.String(), nullable=True))
    op.drop_column('video', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('video', 'video_title')
    # ### end Alembic commands ###
